notifications:
  on_success: change
  on_failure: change

branches:
  only:
    - master
    - develop
    - test

sudo: required
services:
  - postgresql

language: java
jdk:
  - oraclejdk10
  - openjdk10

before_install:
  - chmod +x ./gradle/wrapper/gradle-wrapper.jar
  - chmod +x ./gradlew

before_script:
  - psql -c "create user smart_greenhouse_user with password 'smart_greenhouse_password';" -U postgres
  - psql -c "create database smart_greenhouse_db;" -U postgres
  - psql -c "grant all on database smart_greenhouse_db to smart_greenhouse_user;" -U postgres

script:
  - ./gradlew build
  - ./gradlew test
