notifications:
  on_success: change
  on_failure: change

branches:
  only:
    - master
    - develop

sudo: required
services:
  - postgresql

before_script:
  - psql -c "create user smart-greenhouse-user with password 'smart-greenhouse-password';" -U postgres
  - psql -c "create database smart-greenhouse-db;" -U postgres

language: java
jdk:
  - oraclejdk10
  - openjdk10

script:
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - chmod +x ./gradlew && ./gradlew build

