notifications:
  on_success: change
  on_failure: change

branches:
  only:
    - master
    - develop

sudo: required
services:
  - postgresql

language: java
jdk:
  - oraclejdk10
  - openjdk10

before_install:
  - chmod +x ./gradle/wrapper/gradle-wrapper.jar
  - chmod +x ./gradlew

before_script:
  - psql -c "create user 'user' with password 'password';" -U postgres
  - psql -c "create database 'smart-greenhouse-db';" -U postgres

script:
  - ./gradlew build
